### ISSUE TITLE
Unable to resolve host

### ISSUE THREAD

**Issue by tanshiqi** [Evaneos/ssh-action#1]
My config file is:
```
- name: Connect Server
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts: Intranet.site
          private_key: ${{ secrets.PRIVATE_SSH_KEY }}
          ssh_config: |
            Host Intranet.site
              ForwardAgent yes
              HostName 172.16.x.x
              ProxyJump root@bastion
          commands: |
            echo "I can run..."
            echo "...multiple commands"
```
Bastion server is on public network.
But action returns "Unable to resolve host 'Intranet.site'". Seems that ssh_config not in effect. What the problem?
Thx

**Comment by fhuitelec** [comment]
Hi, sorry for the ~2-year delay to get an answer.

As you can guess, the action [is not maintained](https://github.com/Evaneos/ssh-action/commit/7773df5a5a3cc1a5c889c8026555780203584324) anymore so I'm closing the issue.
