### ISSUE TITLE
got timed out Error

### ISSUE THREAD

**Issue by daiwa233** [Evaneos/ssh-action#2]
![image](https://user-images.githubusercontent.com/50663255/102716621-02316600-4318-11eb-8e9e-80c3d36dad5e.png)

with the config above, I often got the timed out error. But after check the web server status, the command had been excuted

![image](https://user-images.githubusercontent.com/50663255/102716640-2725d900-4318-11eb-8acb-3fb6d95c2e9f.png)

**Comment by fhuitelec** [comment]
Hi, sorry for the 1-year delay to get an answer.

As you can guess, the action [is not maintained](https://github.com/Evaneos/ssh-action/commit/7773df5a5a3cc1a5c889c8026555780203584324) anymore so I'm closing the issue.
